version: "3"
services:
  postgres:
    image: postgres:16rc1
    container_name: ${database_container_name}
    hostname: ${database_container_name}
    restart: always
    environment:
      - POSTGRES_DB=${database_name}
      - POSTGRES_USER=${database_user}
      - POSTGRES_PASSWORD=${database_password}
    ports:
      - ${database_port}:${database_port}
    volumes: 
      - postgres:/var/lib/postgresql/data
      - ./Database:/docker-entrypoint-initdb.d
volumes:
  postgres:
    driver: local
